language: node_js
node_js:
  - node
branches:
  only:
    - master
install:
  - yarn
script:
  - npm run build
  - npm run test
before_deploy:
  - pwd
deploy:
  provider: npm
  edge: true
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: false
    repo: Linkontoask/html-template
