declare module 'html-minifier-terser' {
  type minify = boolean | Function | object
  export interface MiniOptions {
    collapseWhitespace?: boolean
    caseSensitive?: boolean
    collapseBooleanAttributes?: boolean
    collapseInlineTagWhitespace?: boolean
    conservativeCollapse?: boolean
    continueOnParseError?: boolean
    customAttrAssign?: any[]
    customAttrCollapse?: RegExp
    customAttrSurround?: any[]
    customEventAttributes?: RegExp[]
    decodeEntities?: boolean
    html5?: boolean
    ignoreCustomComments?: RegExp[]
    ignoreCustomFragments?: RegExp[]
    includeAutoGeneratedTags?: boolean
    keepClosingSlash?: boolean
    maxLineLength?: number
    minifyCSS?: minify
    minifyJS?: minify
    minifyURLs?: minify
    preserveLineBreaks?: boolean
    preventAttributesEscaping?: boolean
    processConditionalComments?: boolean
    processScripts?: any[]
    quoteCharacter?: string
    removeAttributeQuotes?: boolean
    removeComments?: boolean
    removeEmptyAttributes?: boolean | Function
    removeEmptyElements?: boolean
    removeOptionalTags?: boolean
    removeRedundantAttributes?: boolean
    removeScriptTypeAttributes?: boolean
    removeStyleLinkTypeAttributes?: boolean
    removeTagWhitespace?: boolean
    sortAttributes?: boolean
    sortClassName?: boolean
    trimCustomFragments?: boolean
    useShortDoctype?: boolean
  }
  export function minify(html: string, options: MiniOptions): any
}
